import io
from fastapi.testclient import TestClient
from main import app

client = TestClient(app)

SAMPLE_DOC_TEXT = """# DataMind AI Architecture and Enterprise Security Overview

DataMind AI is an enterprise-grade intelligent assistant. The system uses FastAPI for asynchronous API throughput and PostgreSQL for transactional data.

## Security Architecture
DataMind AI operates under a strict Zero-Trust principle. All Text-to-SQL operations are executed in Read-Only mode to prevent data corruption. No destructive DDL or DML queries such as DROP or DELETE are ever allowed.

## Document Intelligence
The platform integrates semantic text chunking and vector storage with ChromaDB. Answers generated by the assistant must explicitly cite the document name and page number to eliminate hallucination.
"""


def test_rag_upload_and_index_document():
    doc_file = io.BytesIO(SAMPLE_DOC_TEXT.encode("utf-8"))
    response = client.post(
        "/api/v1/rag/upload",
        files={"file": ("security_policy.md", doc_file, "text/markdown")}
    )
    assert response.status_code == 200
    data = response.json()
    assert data["success"] is True
    assert data["document"]["document_name"] == "security_policy.md"
    assert data["document"]["total_chunks"] >= 1
    assert "document_id" in data["document"]


def test_rag_list_documents():
    response = client.get("/api/v1/rag/documents")
    assert response.status_code == 200
    docs = response.json()
    assert isinstance(docs, list)
    assert len(docs) >= 1
    assert any(d["document_name"] == "security_policy.md" for d in docs)


def test_rag_query_with_source_citation():
    # Ask question related to security
    response = client.post(
        "/api/v1/rag/query",
        json={"question": "What is the security architecture principle and what queries are forbidden?"}
    )
    assert response.status_code == 200
    data = response.json()
    assert data["retrieved_chunks_count"] >= 1
    assert len(data["citations"]) >= 1
    assert "security_policy.md" in data["citations"][0]["document_name"]
    assert "page_number" in data["citations"][0]
    assert data["citations"][0]["relevance_percentage"] > 0
    assert "Zero-Trust" in data["answer"] or "Read-Only" in data["answer"] or "security_policy.md" in data["answer"]


def test_rag_delete_document():
    # Get doc ID
    list_res = client.get("/api/v1/rag/documents")
    doc_id = list_res.json()[0]["document_id"]

    del_res = client.delete(f"/api/v1/rag/documents/{doc_id}")
    assert del_res.status_code == 200
    assert del_res.json()["success"] is True

    # Verify deletion
    after_res = client.get("/api/v1/rag/documents")
    assert not any(d["document_id"] == doc_id for d in after_res.json())
